/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log In */
        post: operations["log_in"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log Out */
        get: operations["log_out"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bloodbank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Bloodbanks
         * @description Lists all blood banks in the system, even the ones the logged in user is not adminstrator for
         *
         *     TODO:
         *     - enhance with opening hours information
         *     - allow admins to list which people are admins
         */
        get: operations["list_bloodbanks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bloodbank/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Bloodbank
         * @description Creates a new bloodbank with the logged in admin user as an administrator
         */
        post: operations["create_bloodbank"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bloodbank/{bloodbank_id}/admin/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Admin To Bloodbank
         * @description Add another admin to a blood bank the logged in user is administrator for
         */
        post: operations["add_admin_to_bloodbank"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bloodbank/{bloodbank_id}/admin/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Admin From Bloodbank
         * @description Remove an admin from a blood bank the logged in user is administrator for
         *
         *     The user can remove themselves.
         *     The user can't remove the last admin of a blood bank.
         */
        delete: operations["remove_admin_from_bloodbank"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bloodbank/{bloodbank_id}/appointment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bloodbank Appointments
         * @description Show appointments for blood bank.
         *
         *     By default only the ones scheduled after 00:00 in Oslo on the same day
         */
        get: operations["bloodbank_appointments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/appointment/{appointment_id}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Appointment Add Note */
        post: operations["appointment_add_note"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/appointment/{appointment_id}/donation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Appointment Register Donation */
        post: operations["appointment_register_donation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/donor/{donor_id}/form/interview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Interview */
        post: operations["register_interview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/donor/{donor_id}/form/donation-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Donation Test */
        post: operations["register_donation_test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find All */
        get: operations["find_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/appointment/{appointment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update
         * @description Update an appointment, either changing its booking slot or cancelling it altogether
         *
         *     This action can be performed by the donor or an admin at the blood bank(s) in question
         *
         *     TODO:
         *     - validate that requested bookingslot works
         *     - add appointment note entry documenting the change
         */
        patch: operations["update"];
        trace?: never;
    };
    "/appointment/{appointment_id}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Note */
        post: operations["add_note"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookingslot/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Available */
        get: operations["get_available"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookingslot/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book */
        post: operations["book"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/testresult": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Testresults */
        get: operations["get_all_testresults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/testresult/{testresult_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Testresult */
        get: operations["get_testresult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bloodbank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Bloodbanks */
        get: operations["get_all_bloodbanks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddNoteRequest */
        AddNoteRequest: {
            /** Message */
            message: string;
        };
        /** AppointmentDTO */
        AppointmentDTO: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /**
             * Duration
             * Format: duration
             */
            duration: string;
            /** Bloodbank Name */
            bloodbank_name: string;
            /** Cancelled */
            cancelled: boolean;
            /** Notes */
            notes: components["schemas"]["NoteDTO"][];
        };
        /** AppointmentNote */
        AppointmentNote: {
            /** Message */
            message: string;
        };
        /** AppointmentNoteType */
        AppointmentNoteType: {
            /** Author User Id */
            author_user_id: number;
            /** Author Name */
            author_name: string;
            /** Message */
            message: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** AppointmentType */
        AppointmentType: {
            /** Appointment Id */
            appointment_id: number;
            /** Appointment Cancelled */
            appointment_cancelled: boolean;
            /** Donor Id */
            donor_id: number;
            donor_blood_type: components["schemas"]["BloodType"] | null;
            /** Donor Name */
            donor_name: string;
            /** Donor Email */
            donor_email: string;
            /** Donor Phone */
            donor_phone: string;
            /** Notes */
            notes: components["schemas"]["AppointmentNoteType"][];
            /** Donations */
            donations: components["schemas"]["DonationType"][];
        };
        /** AppointmentUpdateDTO */
        AppointmentUpdateDTO: {
            /** Id */
            id: number;
            /** Bookingslot Id */
            bookingslot_id: number;
            /** Cancelled */
            cancelled: boolean;
            /** Donor Id */
            donor_id: number;
        };
        /** AppointmentUpdateRequest */
        AppointmentUpdateRequest: {
            /** Bookingslot Id */
            bookingslot_id: number;
            /** Cancelled */
            cancelled: boolean;
        };
        /** AvailableBookingSlot */
        AvailableBookingSlot: {
            /** Id */
            id: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /**
             * Duration
             * Format: duration
             */
            duration: string;
            /** Capacity */
            capacity: number;
            /** Bloodbank Id */
            bloodbank_id: number;
            /** Bloodbank Name */
            bloodbank_name: string;
            /** Location Id */
            location_id: number;
            /** Valid */
            valid: boolean;
        };
        /**
         * BloodType
         * @enum {string}
         */
        BloodType: "O+" | "O-" | "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-";
        /** BloodbankResponse */
        BloodbankResponse: {
            /** Bloodbank Id */
            bloodbank_id: number;
            /** Name */
            name: string;
            /** Street Name */
            street_name: string;
            /** Street Number */
            street_number: string;
            /** Postal Code */
            postal_code: string;
            /** City */
            city: string;
            /** Country */
            country: string;
            /** User Has Admin Access */
            user_has_admin_access: boolean;
        };
        /** BookAppointmentRequest */
        BookAppointmentRequest: {
            /** Bookingslot Id */
            bookingslot_id: number;
        };
        /** BookBookingslotRow */
        BookBookingslotRow: {
            /** Id */
            id: number;
            /** Donor Id */
            donor_id: number;
            /** Bookingslot Id */
            bookingslot_id: number;
            /** Cancelled */
            cancelled: boolean;
        };
        /** BookingSlotType */
        BookingSlotType: {
            /** Bookingslot Id */
            bookingslot_id: number;
            /**
             * Bookingslot Time
             * Format: date-time
             */
            bookingslot_time: string;
            /**
             * Bookingslot Duration
             * Format: duration
             */
            bookingslot_duration: string;
            /** Bookingslot Remaining Capacity */
            bookingslot_remaining_capacity: number;
            /** Appointments */
            appointments: components["schemas"]["AppointmentType"][];
        };
        /** CreateBloodBankRequest */
        CreateBloodBankRequest: {
            /** Name */
            name: string;
            /** Street Name */
            street_name: string;
            /** Street Number */
            street_number: string;
            /** Postal Code */
            postal_code: string;
            /** City */
            city: string;
            /**
             * Country
             * @default NO
             */
            country: string;
            /** Loc Lat */
            loc_lat: number;
            /** Loc Lon */
            loc_lon: number;
        };
        /** DonationTestDetailsRow */
        DonationTestDetailsRow: {
            /** Id */
            id: number;
            /** Donor Id */
            donor_id: number;
            /** Form Id */
            form_id: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /**
             * Validity Duration
             * Format: duration
             */
            validity_duration: string;
            /** Invalidated */
            invalidated: boolean;
            /** Ok To Donate */
            ok_to_donate: boolean;
            /** Donation Test Id */
            donation_test_id: number | null;
            /** Donation Id */
            donation_id: number;
            /** Tester Admin Id */
            tester_admin_id: number;
            /** Appointment Id */
            appointment_id: number;
            /** Amount Ml */
            amount_ml: number;
            /** Is Blood Not Plasma */
            is_blood_not_plasma: boolean;
            /** Tester Admin Name */
            tester_admin_name: string;
        };
        /** DonationTestResultRow */
        DonationTestResultRow: {
            /** Id */
            id: number;
            /** Donor Id */
            donor_id: number;
            /** Form Id */
            form_id: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /**
             * Validity Duration
             * Format: duration
             */
            validity_duration: string;
            /** Invalidated */
            invalidated: boolean;
            /** Donation Test Id */
            donation_test_id: number | null;
            /** Admin Name */
            admin_name: string;
        };
        /** DonationType */
        DonationType: {
            /** Donation Id */
            donation_id: number;
            /** Amount Ml */
            amount_ml: number;
            /** Is Blood Not Plasma */
            is_blood_not_plasma: boolean;
        };
        /** EntryFormDetailsRow */
        EntryFormDetailsRow: {
            /** Id */
            id: number;
            /** Donor Id */
            donor_id: number;
            /** Form Id */
            form_id: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /**
             * Validity Duration
             * Format: duration
             */
            validity_duration: string;
            /** Invalidated */
            invalidated: boolean;
            /** Ok To Donate */
            ok_to_donate: boolean;
            /** Entry Form Id */
            entry_form_id: number | null;
        };
        /** EntryFormResultRow */
        EntryFormResultRow: {
            /** Id */
            id: number;
            /** Donor Id */
            donor_id: number;
            /** Form Id */
            form_id: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /**
             * Validity Duration
             * Format: duration
             */
            validity_duration: string;
            /** Invalidated */
            invalidated: boolean;
            /** Entry Form Id */
            entry_form_id: number | null;
        };
        /** GetAllBloodBanksRow */
        GetAllBloodBanksRow: {
            /** Bloodbank Id */
            bloodbank_id: number;
            /** Name */
            name: string;
            /** Street Name */
            street_name: string;
            /** Street Number */
            street_number: string;
            /** Postal Code */
            postal_code: string;
            /** City */
            city: string;
            /** Country */
            country: string;
            /** User Has Admin Access */
            user_has_admin_access: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterviewDetailsRow */
        InterviewDetailsRow: {
            /** Id */
            id: number;
            /** Donor Id */
            donor_id: number;
            /** Form Id */
            form_id: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /**
             * Validity Duration
             * Format: duration
             */
            validity_duration: string;
            /** Invalidated */
            invalidated: boolean;
            /** Ok To Donate */
            ok_to_donate: boolean;
            /** Interview Id */
            interview_id: number | null;
            /** Interviewer Admin Id */
            interviewer_admin_id: number;
            /** Interviewer Admin Name */
            interviewer_admin_name: string;
        };
        /** InterviewResponse */
        InterviewResponse: {
            /** Interviews */
            interviews: components["schemas"]["InterviewResultRow"][];
            /** Entry Forms */
            entry_forms: components["schemas"]["EntryFormResultRow"][];
            /** Donation Tests */
            donation_tests: components["schemas"]["DonationTestResultRow"][];
        };
        /** InterviewResultRow */
        InterviewResultRow: {
            /** Id */
            id: number;
            /** Donor Id */
            donor_id: number;
            /** Form Id */
            form_id: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /**
             * Validity Duration
             * Format: duration
             */
            validity_duration: string;
            /** Invalidated */
            invalidated: boolean;
            /** Interview Id */
            interview_id: number | null;
            /** Admin Name */
            admin_name: string;
        };
        /** LoginRequestData */
        LoginRequestData: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MutateBloodbankAdminsRequest */
        MutateBloodbankAdminsRequest: {
            /** Admin Id */
            admin_id: number;
        };
        /** NoteDTO */
        NoteDTO: {
            /** Author User Id */
            author_user_id: number;
            /** Author Name */
            author_name: string;
            /** Message */
            message: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** RegisterDonationRequest */
        RegisterDonationRequest: {
            /** Amount Ml */
            amount_ml: number;
            /**
             * Is Blood Not Plasma
             * @default true
             */
            is_blood_not_plasma: boolean;
        };
        /** RegisterDonationTestRequest */
        RegisterDonationTestRequest: {
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at?: string;
            /** Ok To Donate */
            ok_to_donate: boolean;
            /**
             * Validity Duration
             * Format: duration
             */
            validity_duration: string;
            /** Donation Id */
            donation_id: number;
        };
        /** RegisterInterviewRequest */
        RegisterInterviewRequest: {
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at?: string;
            /** Ok To Donate */
            ok_to_donate: boolean;
            /**
             * Validity Duration
             * Format: duration
             */
            validity_duration: string;
        };
        /** UserInfo */
        UserInfo: {
            /** User Id */
            user_id: number;
            /** User Name */
            user_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    log_in: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestData"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. Incorrect email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_out: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
        };
    };
    list_bloodbanks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAllBloodBanksRow"][];
                };
            };
        };
    };
    create_bloodbank: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBloodBankRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_admin_to_bloodbank: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bloodbank_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutateBloodbankAdminsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_admin_from_bloodbank: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bloodbank_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutateBloodbankAdminsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bloodbank_appointments: {
        parameters: {
            query?: {
                after?: string | null;
                before?: string | null;
                show_cancelled?: boolean;
            };
            header?: never;
            path: {
                bloodbank_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingSlotType"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    appointment_add_note: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddNoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    appointment_register_donation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDonationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_interview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                donor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInterviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_donation_test: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                donor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDonationTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentDTO"][];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentUpdateDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_note: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentNote"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_available: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableBookingSlot"][];
                };
            };
        };
    };
    book: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookAppointmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookBookingslotRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_testresults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewResponse"];
                };
            };
        };
    };
    get_testresult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                testresult_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewDetailsRow"] | components["schemas"]["DonationTestDetailsRow"] | components["schemas"]["EntryFormDetailsRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_bloodbanks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BloodbankResponse"][];
                };
            };
        };
    };
}
