name: Commons

on:
  push:
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/commons.yml"

permissions:
  contents: read

jobs:
  verify-swagger-json:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: GENERATE_SWAGGER_ONLY="true" uv run uvicorn app.main:app
      - run: |
          if [[ ! -z $(git diff --name-only) ]]; then
            echo "Error: swagger json in frontend not up to date"
            exit 1
          fi
