# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: admin.sql
import datetime
import pydantic
from typing import Any, AsyncIterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from app.db.sqlc import models


ADD_APPOINTMENT_NOTE = """-- name: add_appointment_note \\:exec
INSERT INTO appointment_note (appointment_id, author_id, message, time)
VALUES (:p1, :p2, :p3, NOW())
"""


ADD_BLOOD_BANK_ADMIN = """-- name: add_blood_bank_admin \\:exec
INSERT INTO bloodbank_admin (bloodbank_id, admin_id)
VALUES (:p1, :p2)
"""


CREATE_BLOOD_BANK = """-- name: create_blood_bank \\:one
WITH addr AS (
    INSERT INTO address (street_name, street_number, postal_code, city, country)
    VALUES (:p1, :p2, :p3, :p4, :p5)
    RETURNING id
),
loc AS (
    INSERT INTO location (latitude, longitude, address_id)
    VALUES (:p6, :p7, (SELECT id FROM addr))
    RETURNING id
),
bank AS (
    INSERT INTO bloodbank (name, location_id)
    VALUES (:p8, (SELECT id FROM loc))
    RETURNING id
)
INSERT INTO bloodbank_admin (bloodbank_id, admin_id)
VALUES ((SELECT id FROM bank), :p9)
RETURNING bloodbank_id
"""


class CreateBloodBankParams(pydantic.BaseModel):
    street_name: str
    street_number: str
    postal_code: str
    city: str
    country: str
    latitude: float
    longitude: float
    name: str
    admin_id: int


GET_ALL_BLOOD_BANKS = """-- name: get_all_blood_banks \\:many
SELECT b.id as bloodbank_id, b.name, a.street_name, a.street_number, a.postal_code, a.city, a.country,
    COUNT(bba.admin_id) > 0 AS user_has_admin_access
FROM bloodbank b
INNER JOIN location l ON b.location_id = l.id
INNER JOIN address a ON l.address_id = a.id
LEFT JOIN bloodbank_admin bba ON (b.id = bba.bloodbank_id AND bba.admin_id = :p1)
GROUP BY b.id, a.id
"""


class GetAllBloodBanksRow(pydantic.BaseModel):
    bloodbank_id: int
    name: str
    street_name: str
    street_number: str
    postal_code: str
    city: str
    country: str
    user_has_admin_access: bool


GET_APPOINTMENTS_AT_BLOOD_BANK = """-- name: get_appointments_at_blood_bank \\:many
SELECT bs.id as bookingslot_id, bs.time as bookingslot_time,
    bs.duration as bookingslot_duration,
    bs.capacity as bookingslot_remaining_capacity,
    json_agg(json_build_object(
        'appointment_id', a.id,
        'appointment_cancelled', a.cancelled,
        'donor_id', d.id,
        'donor_blood_type', d.blood_type,
        'donor_name', u.name,
        'donor_email', u.email,
        'donor_phone', u.phone_number,
        'notes', (
            SELECT COALESCE(json_agg(json_build_object(
                'author_user_id', nu.id,
                'author_name', nu.name,
                'message', an.message,
                'time', an.time
            ) ORDER BY an.time DESC), '[]'\\:\\:json)
            FROM appointment_note an
            INNER JOIN "user" nu ON an.author_id = nu.id
            WHERE an.appointment_id = a.id
        ),
        'donations', (
            SELECT COALESCE(json_agg(json_build_object(
                'donation_id', dn.id,
                'amount_ml', dn.amount_ml,
                'is_blood_not_plasma', dn.is_blood_not_plasma
                -- TODO\\: testing status
            ) ORDER BY dn.id), '[]'\\:\\:json)
            FROM donation dn
            WHERE dn.appointment_id = a.id
        )
    )) as appointments
FROM bookingslot bs
INNER JOIN appointment a ON a.bookingslot_id = bs.id
INNER JOIN donor d ON a.donor_id = d.id
INNER JOIN "user" u ON u.donor_id = d.id
WHERE bs.bloodbank_id = :p1 AND bs.time >= :p2
    AND (:p3\\:\\:TIMESTAMP WITH TIME ZONE IS NULL
        OR :p3 >= bs.time)
    AND (:p4\\:\\:BOOLEAN OR NOT a.cancelled)
GROUP BY bs.id
"""


class GetAppointmentsAtBloodBankRow(pydantic.BaseModel):
    bookingslot_id: int
    bookingslot_time: datetime.datetime
    bookingslot_duration: datetime.timedelta
    bookingslot_remaining_capacity: int
    appointments: Any


GET_DONATION_INFO = """-- name: get_donation_info \\:one
SELECT a.donor_id, b.id as bloodbank_id
FROM donation d
INNER JOIN appointment a ON d.appointment_id = a.id
INNER JOIN bookingslot bs ON a.bookingslot_id = bs.id
INNER JOIN bloodbank b ON bs.bloodbank_id = b.id
WHERE d.id = :p1
"""


class GetDonationInfoRow(pydantic.BaseModel):
    donor_id: int
    bloodbank_id: int


REGISTER_DONATION = """-- name: register_donation \\:one
INSERT INTO donation (appointment_id, amount_ml, is_blood_not_plasma)
VALUES (:p1, :p2, :p3)
RETURNING id
"""


REGISTER_DONATION_TEST = """-- name: register_donation_test \\:exec
WITH dt AS (
    INSERT INTO donation_test (donation_id, tester_admin_id)
    VALUES (:p1, :p2)
    RETURNING id
), f AS (
    INSERT INTO form (ok_to_donate, donation_test_id)
    VALUES (:p4, (SELECT id FROM dt))
    RETURNING id
)
INSERT INTO test_result (donor_id, form_id, time, validity_duration)
VALUES (:p3, (SELECT id FROM f), :p5, :p6)
"""


class RegisterDonationTestParams(pydantic.BaseModel):
    donation_id: int
    tester_admin_id: int
    donor_id: int
    ok_to_donate: bool
    time: datetime.datetime
    validity_duration: datetime.timedelta


REGISTER_INTERVIEW = """-- name: register_interview \\:exec
WITH iv AS (
    INSERT INTO interview (interviewer_admin_id)
    VALUES (:p1) RETURNING id
), f AS (
    INSERT INTO form (ok_to_donate, interview_id)
    VALUES (:p3, (SELECT id FROM iv))
    RETURNING id
)
INSERT INTO test_result (donor_id, form_id, time, validity_duration)
VALUES (:p2, (SELECT id FROM f), :p4, :p5)
"""


class RegisterInterviewParams(pydantic.BaseModel):
    interviewer_admin_id: int
    donor_id: int
    ok_to_donate: bool
    time: datetime.datetime
    validity_duration: datetime.timedelta


REMOVE_BLOOD_BANK_ADMIN = """-- name: remove_blood_bank_admin \\:one
DELETE FROM bloodbank_admin bba
WHERE bba.bloodbank_id = :p1 AND
    bba.admin_id = :p2 AND
    (SELECT count(id) FROM bloodbank_admin WHERE bloodbank_id = :p1) > 1
RETURNING bba.admin_id
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def add_appointment_note(self, *, appointment_id: int, author_id: int, message: str) -> None:
        await self._conn.execute(sqlalchemy.text(ADD_APPOINTMENT_NOTE), {"p1": appointment_id, "p2": author_id, "p3": message})

    async def add_blood_bank_admin(self, *, bloodbank_id: int, admin_id: int) -> None:
        await self._conn.execute(sqlalchemy.text(ADD_BLOOD_BANK_ADMIN), {"p1": bloodbank_id, "p2": admin_id})

    async def create_blood_bank(self, arg: CreateBloodBankParams) -> Optional[int]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_BLOOD_BANK), {
            "p1": arg.street_name,
            "p2": arg.street_number,
            "p3": arg.postal_code,
            "p4": arg.city,
            "p5": arg.country,
            "p6": arg.latitude,
            "p7": arg.longitude,
            "p8": arg.name,
            "p9": arg.admin_id,
        })).first()
        if row is None:
            return None
        return row[0]

    async def get_all_blood_banks(self, *, admin_id: int) -> AsyncIterator[GetAllBloodBanksRow]:
        result = await self._conn.stream(sqlalchemy.text(GET_ALL_BLOOD_BANKS), {"p1": admin_id})
        async for row in result:
            yield GetAllBloodBanksRow(
                bloodbank_id=row[0],
                name=row[1],
                street_name=row[2],
                street_number=row[3],
                postal_code=row[4],
                city=row[5],
                country=row[6],
                user_has_admin_access=row[7],
            )

    async def get_appointments_at_blood_bank(self, *, bloodbank_id: int, after: datetime.datetime, before: Optional[datetime.datetime], show_cancelled: bool) -> AsyncIterator[GetAppointmentsAtBloodBankRow]:
        result = await self._conn.stream(sqlalchemy.text(GET_APPOINTMENTS_AT_BLOOD_BANK), {
            "p1": bloodbank_id,
            "p2": after,
            "p3": before,
            "p4": show_cancelled,
        })
        async for row in result:
            yield GetAppointmentsAtBloodBankRow(
                bookingslot_id=row[0],
                bookingslot_time=row[1],
                bookingslot_duration=row[2],
                bookingslot_remaining_capacity=row[3],
                appointments=row[4],
            )

    async def get_donation_info(self, *, donation_id: int) -> Optional[GetDonationInfoRow]:
        row = (await self._conn.execute(sqlalchemy.text(GET_DONATION_INFO), {"p1": donation_id})).first()
        if row is None:
            return None
        return GetDonationInfoRow(
            donor_id=row[0],
            bloodbank_id=row[1],
        )

    async def register_donation(self, *, appointment_id: int, amount_ml: float, is_blood_not_plasma: bool) -> Optional[int]:
        row = (await self._conn.execute(sqlalchemy.text(REGISTER_DONATION), {"p1": appointment_id, "p2": amount_ml, "p3": is_blood_not_plasma})).first()
        if row is None:
            return None
        return row[0]

    async def register_donation_test(self, arg: RegisterDonationTestParams) -> None:
        await self._conn.execute(sqlalchemy.text(REGISTER_DONATION_TEST), {
            "p1": arg.donation_id,
            "p2": arg.tester_admin_id,
            "p3": arg.donor_id,
            "p4": arg.ok_to_donate,
            "p5": arg.time,
            "p6": arg.validity_duration,
        })

    async def register_interview(self, arg: RegisterInterviewParams) -> None:
        await self._conn.execute(sqlalchemy.text(REGISTER_INTERVIEW), {
            "p1": arg.interviewer_admin_id,
            "p2": arg.donor_id,
            "p3": arg.ok_to_donate,
            "p4": arg.time,
            "p5": arg.validity_duration,
        })

    async def remove_blood_bank_admin(self, *, bloodbank_id: int, admin_id: int) -> Optional[int]:
        row = (await self._conn.execute(sqlalchemy.text(REMOVE_BLOOD_BANK_ADMIN), {"p1": bloodbank_id, "p2": admin_id})).first()
        if row is None:
            return None
        return row[0]
