# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: admin.sql
import datetime
import pydantic
from typing import Any, AsyncIterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from app.db.sqlc import models


ADD_BLOOD_BANK_ADMIN = """-- name: add_blood_bank_admin \\:exec
INSERT INTO bloodbank_admin (bloodbank_id, admin_id)
VALUES (:p1, :p2)
"""


CREATE_BLOOD_BANK = """-- name: create_blood_bank \\:one
WITH addr AS (
    INSERT INTO address (street_name, street_number, postal_code, city, country)
    VALUES (:p1, :p2, :p3, :p4, :p5)
    RETURNING id
),
loc AS (
    INSERT INTO location (latitude, longitude, address_id)
    VALUES (:p6, :p7, addr.id)
    RETURNING id
),
bank AS (
    INSERT INTO bloodbank (name, location_id)
    VALUES (:p8, loc.id)
    RETURNING id
)
INSERT INTO bloodbank_admin (bloodbank_id, admin_id)
VALUES (bank.id, :p9)
RETURNING bloodbank_id
"""


class CreateBloodBankParams(pydantic.BaseModel):
    street_name: str
    street_number: str
    postal_code: str
    city: str
    country: str
    latitude: float
    longitude: float
    name: str
    admin_id: int


GET_ALL_BLOOD_BANKS = """-- name: get_all_blood_banks \\:many
SELECT b.name, a.street_name, a.street_number, a.postal_code, a.city, a.country,
    COUNT(bba.admin_id) > 0 AS has_admin
FROM bloodbank b
INNER JOIN location l ON b.location_id = l.id
INNER JOIN address a ON l.address_id = a.id
LEFT JOIN bloodbank_admin bba ON (b.id = bba.bloodbank_id AND bba.admin_id = :p1)
GROUP BY b.id
"""


class GetAllBloodBanksRow(pydantic.BaseModel):
    name: str
    street_name: str
    street_number: str
    postal_code: str
    city: str
    country: str
    has_admin: bool


GET_APPOINTMENTS_AT_BLOOD_BANK = """-- name: get_appointments_at_blood_bank \\:many
SELECT bs.id as bookingslot_id, bs.time as bookingslot_time,
    bs.duration as bookingslot_duration,
    bs.capacity as bookingslot_remaining_capacity,
    json_agg(json_build_object(
        'appointment_id', a.id,
        'appointment_cancelled', a.cancelled,
        'donor_id', d.id,
        'donor_blood_type', d.blood_type,
        'donor_name', u.name,
        'donor_email', u.email,
        'donor_phone', u.phone_number
    )) as appointments
    FROM bookingslot bs
INNER JOIN appointment a ON a.bookingslot_id = bs.id
INNER JOIN donor d ON a.donor_id = d.id
INNER JOIN "user" u ON u.donor_id = d.id
WHERE bs.bloodbank_id = :p1 AND bs.time >= :p2
    AND (:p3\\:\\:TIMESTAMP WITH TIME ZONE IS NULL
        OR :p3 >= bs.time)
    AND (:p4\\:\\:BOOLEAN OR NOT a.cancelled)
GROUP BY bs.id
"""


class GetAppointmentsAtBloodBankRow(pydantic.BaseModel):
    bookingslot_id: int
    bookingslot_time: datetime.datetime
    bookingslot_duration: datetime.timedelta
    bookingslot_remaining_capacity: int
    appointments: Any


REMOVE_BLOOD_BANK_ADMIN = """-- name: remove_blood_bank_admin \\:exec
WITH admin_ct AS (
    SELECT count(id) FROM bloodbank_admin
    WHERE bloodbank_id = :p1
)
DELETE FROM bloodbank_admin bba
WHERE bba.bloodbank_id = :p1 AND
    bba.admin_id = :p2 AND admin_ct > 1
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def add_blood_bank_admin(self, *, bloodbank_id: int, admin_id: int) -> None:
        await self._conn.execute(sqlalchemy.text(ADD_BLOOD_BANK_ADMIN), {"p1": bloodbank_id, "p2": admin_id})

    async def create_blood_bank(self, arg: CreateBloodBankParams) -> Optional[int]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_BLOOD_BANK), {
            "p1": arg.street_name,
            "p2": arg.street_number,
            "p3": arg.postal_code,
            "p4": arg.city,
            "p5": arg.country,
            "p6": arg.latitude,
            "p7": arg.longitude,
            "p8": arg.name,
            "p9": arg.admin_id,
        })).first()
        if row is None:
            return None
        return row[0]

    async def get_all_blood_banks(self, *, admin_id: int) -> AsyncIterator[GetAllBloodBanksRow]:
        result = await self._conn.stream(sqlalchemy.text(GET_ALL_BLOOD_BANKS), {"p1": admin_id})
        async for row in result:
            yield GetAllBloodBanksRow(
                name=row[0],
                street_name=row[1],
                street_number=row[2],
                postal_code=row[3],
                city=row[4],
                country=row[5],
                has_admin=row[6],
            )

    async def get_appointments_at_blood_bank(self, *, bloodbank_id: int, after: datetime.datetime, before: Optional[datetime.datetime], show_cancelled: bool) -> AsyncIterator[GetAppointmentsAtBloodBankRow]:
        result = await self._conn.stream(sqlalchemy.text(GET_APPOINTMENTS_AT_BLOOD_BANK), {
            "p1": bloodbank_id,
            "p2": after,
            "p3": before,
            "p4": show_cancelled,
        })
        async for row in result:
            yield GetAppointmentsAtBloodBankRow(
                bookingslot_id=row[0],
                bookingslot_time=row[1],
                bookingslot_duration=row[2],
                bookingslot_remaining_capacity=row[3],
                appointments=row[4],
            )

    async def remove_blood_bank_admin(self, *, bloodbank_id: int, admin_id: int) -> None:
        await self._conn.execute(sqlalchemy.text(REMOVE_BLOOD_BANK_ADMIN), {"p1": bloodbank_id, "p2": admin_id})
