# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: auth.sql
import pydantic
from typing import Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from app.db.sqlc import models


APPOINTMENT_BELONGS_TO = """-- name: appointment_belongs_to \\:one
SELECT TRUE
FROM appointment a
WHERE a.id = :p1 AND a.donor_id = :p2
"""


GET_USER = """-- name: get_user \\:one
SELECT u.id, u.name, u.email, u.password_hash, u.donor_id, u.admin_id
FROM "user" u WHERE u.email = :p1
"""


class GetUserRow(pydantic.BaseModel):
    id: int
    name: str
    email: str
    password_hash: Optional[str]
    donor_id: Optional[int]
    admin_id: Optional[int]


HAS_ADMIN_AT_BLOOD_BANK = """-- name: has_admin_at_blood_bank \\:one
SELECT TRUE
FROM bloodbank_admin bba
WHERE bba.admin_id = :p1 AND bba.bloodbank_id = :p2
"""


HAS_ADMIN_WHERE_APPOINTMENT_IS = """-- name: has_admin_where_appointment_is \\:one
SELECT TRUE
FROM bloodbank_admin bba
INNER JOIN bookingslot bs ON bs.bloodbank_id = bba.bloodbank_id
INNER JOIN appointment a ON a.bookingslot_id = bs.id
WHERE bba.admin_id = :p1 AND a.id = :p2
"""


TEST_RESULT_BELONGS_TO = """-- name: test_result_belongs_to \\:one
SELECT TRUE
FROM test_result t
	INNER JOIN form f ON t.form_id = f.id
	LEFT JOIN donation_test d ON f.donation_test_id = d.id
	LEFT JOIN donation don ON d.donation_id = don.id
	LEFT JOIN appointment a ON don.appointment_id = a.id
WHERE t.id = :p1 AND t.donor_id = :p2 AND (a.donor_id = :p2 OR a.donor_id IS NULL)
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def appointment_belongs_to(self, *, appointment_id: int, donor_id: int) -> Optional[bool]:
        row = (await self._conn.execute(sqlalchemy.text(APPOINTMENT_BELONGS_TO), {"p1": appointment_id, "p2": donor_id})).first()
        if row is None:
            return None
        return row[0]

    async def get_user(self, *, email: str) -> Optional[GetUserRow]:
        row = (await self._conn.execute(sqlalchemy.text(GET_USER), {"p1": email})).first()
        if row is None:
            return None
        return GetUserRow(
            id=row[0],
            name=row[1],
            email=row[2],
            password_hash=row[3],
            donor_id=row[4],
            admin_id=row[5],
        )

    async def has_admin_at_blood_bank(self, *, admin_id: int, bloodbank_id: int) -> Optional[bool]:
        row = (await self._conn.execute(sqlalchemy.text(HAS_ADMIN_AT_BLOOD_BANK), {"p1": admin_id, "p2": bloodbank_id})).first()
        if row is None:
            return None
        return row[0]

    async def has_admin_where_appointment_is(self, *, admin_id: int, appointment_id: int) -> Optional[bool]:
        row = (await self._conn.execute(sqlalchemy.text(HAS_ADMIN_WHERE_APPOINTMENT_IS), {"p1": admin_id, "p2": appointment_id})).first()
        if row is None:
            return None
        return row[0]

    async def test_result_belongs_to(self, *, testresult_id: int, donor_id: int) -> Optional[bool]:
        row = (await self._conn.execute(sqlalchemy.text(TEST_RESULT_BELONGS_TO), {"p1": testresult_id, "p2": donor_id})).first()
        if row is None:
            return None
        return row[0]
