# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: auth.sql
import pydantic
from typing import Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from app.db.sqlc import models


GET_USER = """-- name: get_user \\:one
SELECT u.id, u.name, u.email, u.password_hash, u.donor_id, u.admin_id
FROM "user" u WHERE u.email = :p1
"""


class GetUserRow(pydantic.BaseModel):
    id: int
    name: str
    email: str
    password_hash: Optional[str]
    donor_id: Optional[int]
    admin_id: Optional[int]


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def get_user(self, *, email: str) -> Optional[GetUserRow]:
        row = (await self._conn.execute(sqlalchemy.text(GET_USER), {"p1": email})).first()
        if row is None:
            return None
        return GetUserRow(
            id=row[0],
            name=row[1],
            email=row[2],
            password_hash=row[3],
            donor_id=row[4],
            admin_id=row[5],
        )
