# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: bloodbank.sql
import pydantic
from typing import AsyncIterator

import sqlalchemy
import sqlalchemy.ext.asyncio

from app.db.sqlc import models


GET_ALL_BLOOD_BANKS = """-- name: get_all_blood_banks \\:many
SELECT b.id as bloodbank_id, b.name, a.street_name, a.street_number, a.postal_code, a.city, a.country,
    COUNT(bba.admin_id) > 0 AS user_has_admin_access
FROM bloodbank b
INNER JOIN location l ON b.location_id = l.id
INNER JOIN address a ON l.address_id = a.id
LEFT JOIN bloodbank_admin bba ON (b.id = bba.bloodbank_id AND bba.admin_id = :p1)
GROUP BY b.id, a.id
"""


class GetAllBloodBanksRow(pydantic.BaseModel):
    bloodbank_id: int
    name: str
    street_name: str
    street_number: str
    postal_code: str
    city: str
    country: str
    user_has_admin_access: bool


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def get_all_blood_banks(self, *, admin_id: int) -> AsyncIterator[GetAllBloodBanksRow]:
        result = await self._conn.stream(sqlalchemy.text(GET_ALL_BLOOD_BANKS), {"p1": admin_id})
        async for row in result:
            yield GetAllBloodBanksRow(
                bloodbank_id=row[0],
                name=row[1],
                street_name=row[2],
                street_number=row[3],
                postal_code=row[4],
                city=row[5],
                country=row[6],
                user_has_admin_access=row[7],
            )
