# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: bookingslot.sql
import datetime
import pydantic
from typing import AsyncIterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from app.db.sqlc import models


BOOK_BOOKINGSLOT = """-- name: book_bookingslot \\:one
WITH slot AS (
    UPDATE bookingslot 
    SET capacity = capacity - 1
    WHERE bookingslot.id = :p2 AND bookingslot.capacity > 0
    RETURNING id as bookingslot_id
)
INSERT INTO appointment (donor_id, bookingslot_id, cancelled)
SELECT :p1, slot.bookingslot_id, FALSE
FROM slot
RETURNING id, donor_id, bookingslot_id, cancelled
"""


class BookBookingslotRow(pydantic.BaseModel):
    id: int
    donor_id: int
    bookingslot_id: int
    cancelled: bool


GET_BOOKING_SLOTS = """-- name: get_booking_slots \\:many
SELECT
    s.id,
    s.time,
    s.duration,
    s.capacity,
    s.bloodbank_id,
    b.name AS bloodbank_name,
	b.location_id
FROM bookingslot s
  INNER JOIN bloodbank b ON b.id = s.bloodbank_id
  ORDER BY s.time ASC
"""


class GetBookingSlotsRow(pydantic.BaseModel):
    id: int
    time: datetime.datetime
    duration: datetime.timedelta
    capacity: int
    bloodbank_id: int
    bloodbank_name: str
    location_id: int


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def book_bookingslot(self, *, donor_id: int, bookingslot_id: int) -> Optional[BookBookingslotRow]:
        row = (await self._conn.execute(sqlalchemy.text(BOOK_BOOKINGSLOT), {"p1": donor_id, "p2": bookingslot_id})).first()
        if row is None:
            return None
        return BookBookingslotRow(
            id=row[0],
            donor_id=row[1],
            bookingslot_id=row[2],
            cancelled=row[3],
        )

    async def get_booking_slots(self) -> AsyncIterator[GetBookingSlotsRow]:
        result = await self._conn.stream(sqlalchemy.text(GET_BOOKING_SLOTS))
        async for row in result:
            yield GetBookingSlotsRow(
                id=row[0],
                time=row[1],
                duration=row[2],
                capacity=row[3],
                bloodbank_id=row[4],
                bloodbank_name=row[5],
                location_id=row[6],
            )
