# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: first_table.sql
from typing import AsyncIterator

import sqlalchemy
import sqlalchemy.ext.asyncio

from app.db.sqlc import models


GET_ALL_ROWS = """-- name: get_all_rows \\:many
SELECT id, a FROM first_table
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def get_all_rows(self) -> AsyncIterator[models.FirstTable]:
        result = await self._conn.stream(sqlalchemy.text(GET_ALL_ROWS))
        async for row in result:
            yield models.FirstTable(
                id=row[0],
                a=row[1],
            )
