# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: free_appointment.sql
import datetime
import pydantic
from typing import AsyncIterator

import sqlalchemy
import sqlalchemy.ext.asyncio

from app.db.sqlc import models


GET_AVAILABLE_APPOINTMENTS = """-- name: get_available_appointments \\:many
SELECT
    fa.id,
    fa.time,
    fa.location_id,
    b.name AS locationname
FROM free_appointments fa
JOIN bloodbank b ON b.id = fa.location_id
ORDER BY fa.time ASC
"""


class GetAvailableAppointmentsRow(pydantic.BaseModel):
    id: int
    time: datetime.datetime
    location_id: int
    locationname: str


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def get_available_appointments(self) -> AsyncIterator[GetAvailableAppointmentsRow]:
        result = await self._conn.stream(sqlalchemy.text(GET_AVAILABLE_APPOINTMENTS))
        async for row in result:
            yield GetAvailableAppointmentsRow(
                id=row[0],
                time=row[1],
                location_id=row[2],
                locationname=row[3],
            )
