# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import pydantic
from typing import Any


class Appointment(pydantic.BaseModel):
    id: Any
    user_id: Any
    time: Any
    location_id: Any


class Bloodbank(pydantic.BaseModel):
    id: Any
    name: Any


class User(pydantic.BaseModel):
    id: Any
    name: Any
