# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import datetime
import pydantic


class Appointment(pydantic.BaseModel):
    id: int
    user_id: int
    time: datetime.datetime
    location_id: int


class Bloodbank(pydantic.BaseModel):
    id: int
    name: str


class User(pydantic.BaseModel):
    id: int
    name: str
