# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: testresults.sql
import datetime
import pydantic
from typing import AsyncIterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from app.db.sqlc import models


TEST_RESULT = """-- name: test_result \\:one
SELECT 
	t.id as id,
	t.donor_id as donor_id,
	t.form_id as form_id,
	t.time as time,
	t.validity_duration as validity_duration,
	t.invalidated as invalidated,
	f.ok_to_donate as ok_to_donate,
	f.interview_id as interview_id,
	f.entry_form_id as entry_form_id,
	f.donation_test_id as donation_test_id,
	i.interviewer_admin_id as interviewer_admin_id,
	d.donation_id as donation_id,
	don.appointment_id as appointment_id,
	don.amount_ml as amount_ml,
	don.is_blood_not_plasma as is_blood_not_plasma
 FROM test_result t
	INNER JOIN form f ON t.form_id = f.id
	LEFT JOIN interview i ON f.interview_id = i.id
	LEFT JOIN entry_form e ON f.entry_form_id = e.id
	LEFT JOIN donation_test d ON f.donation_test_id = d.id
	LEFT JOIN donation don ON d.donation_id = don.id
	WHERE t.id = :p1
"""


class TestResultRow(pydantic.BaseModel):
    id: int
    donor_id: int
    form_id: int
    time: datetime.datetime
    validity_duration: datetime.timedelta
    invalidated: bool
    ok_to_donate: Optional[bool]
    interview_id: Optional[int]
    entry_form_id: Optional[int]
    donation_test_id: Optional[int]
    interviewer_admin_id: Optional[int]
    donation_id: Optional[int]
    appointment_id: Optional[int]
    amount_ml: Optional[float]
    is_blood_not_plasma: Optional[bool]


TEST_RESULTS = """-- name: test_results \\:many
SELECT id, donor_id, form_id, time, validity_duration, invalidated FROM test_result t WHERE t.donor_id = :p1
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def test_result(self, *, testresult_id: int) -> Optional[TestResultRow]:
        row = (await self._conn.execute(sqlalchemy.text(TEST_RESULT), {"p1": testresult_id})).first()
        if row is None:
            return None
        return TestResultRow(
            id=row[0],
            donor_id=row[1],
            form_id=row[2],
            time=row[3],
            validity_duration=row[4],
            invalidated=row[5],
            ok_to_donate=row[6],
            interview_id=row[7],
            entry_form_id=row[8],
            donation_test_id=row[9],
            interviewer_admin_id=row[10],
            donation_id=row[11],
            appointment_id=row[12],
            amount_ml=row[13],
            is_blood_not_plasma=row[14],
        )

    async def test_results(self, *, donor_id: int) -> AsyncIterator[models.TestResult]:
        result = await self._conn.stream(sqlalchemy.text(TEST_RESULTS), {"p1": donor_id})
        async for row in result:
            yield models.TestResult(
                id=row[0],
                donor_id=row[1],
                form_id=row[2],
                time=row[3],
                validity_duration=row[4],
                invalidated=row[5],
            )
